import {StyleSheet} from 'react-native';
import {colors} from '../constants/colors';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.appBackground,
  },
  backgroundGradient: {
    backgroundColor: colors.appBackground,
    bottom: 0,
    left: 0,
    overflow: 'hidden',
    position: 'absolute',
    right: 0,
    top: 0,
  },
  backgroundGlowTop: {
    backgroundColor: 'rgba(17 125 238 / 0.32)',
    borderBottomLeftRadius: 160,
    borderBottomRightRadius: 210,
    height: 300,
    left: -80,
    position: 'absolute',
    right: -40,
    top: -120,
    transform: [{rotate: '-8deg'}],
  },
  backgroundGlowMiddle: {
    backgroundColor: 'rgba(12 98 189 / 0.20)',
    borderRadius: 170,
    height: 340,
    position: 'absolute',
    right: -130,
    top: 150,
    transform: [{rotate: '12deg'}],
    width: 280,
  },
  backgroundGlowBottom: {
    backgroundColor: 'rgba(3 37 78 / 0.72)',
    borderTopLeftRadius: 220,
    borderTopRightRadius: 190,
    bottom: -120,
    height: 280,
    left: -70,
    position: 'absolute',
    right: -70,
  },
  backgroundShade: {
    backgroundColor: 'rgba(0 8 20 / 0.26)',
    bottom: 0,
    height: '42%',
    left: 0,
    position: 'absolute',
    right: 0,
  },
  scrollArea: {
    flex: 1,
  },
  content: {
    gap: 14,
    paddingHorizontal: 18,
  },
  authContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingBottom: 28,
    paddingHorizontal: 18,
  },
  scrollContentBottomSpacing: {
    paddingBottom: 18,
  },
  bottomAppBarWrap: {
    backgroundColor: 'rgba(1 15 32 / 0.92)',
    boxShadow: '0 -8px 20px rgba(0, 8, 20, 0.34)',
    paddingHorizontal: 14,
    paddingTop: 8,
  },
  sectionStack: {
    gap: 14,
  },
  welcomeStage: {
    alignSelf: 'center',
    gap: 24,
    maxWidth: 430,
    width: '100%',
  },
  welcomeMark: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(191 223 255 / 0.12)',
    borderColor: colors.glassBorder,
    borderRadius: 8,
    borderWidth: 1,
    boxShadow: '0 18px 42px rgba(0, 8, 20, 0.34)',
    height: 112,
    justifyContent: 'center',
    overflow: 'hidden',
    transform: [{perspective: 420}, {rotateX: '7deg'}],
    width: 112,
  },
  welcomeMarkPulse: {
    backgroundColor: 'rgba(17 125 238 / 0.26)',
    borderRadius: 78,
    height: 126,
    position: 'absolute',
    right: -40,
    top: -38,
    width: 126,
  },
  welcomeMarkImage: {
    height: 72,
    resizeMode: 'contain',
    width: 72,
  },
  welcomeMarkText: {
    color: colors.white,
    fontSize: 58,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 64,
  },
  welcomeCopy: {
    gap: 10,
  },
  welcomeEyebrow: {
    color: colors.mintLight,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 17,
    textAlign: 'center',
  },
  welcomeTitle: {
    color: colors.white,
    fontSize: 38,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 43,
    textAlign: 'center',
  },
  welcomeSubtitle: {
    color: colors.mintLight,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 22,
    textAlign: 'center',
  },
  welcomeStatsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  welcomeStat: {
    alignItems: 'center',
    backgroundColor: 'rgba(255 255 255 / 0.08)',
    borderColor: 'rgba(191 223 255 / 0.24)',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    minHeight: 82,
    paddingHorizontal: 10,
    paddingVertical: 13,
  },
  welcomeStatValue: {
    color: colors.white,
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 27,
  },
  welcomeStatLabel: {
    color: colors.mintLight,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 16,
  },
  authButtonStack: {
    gap: 10,
  },
  authPrimaryButton: {
    alignItems: 'center',
    backgroundColor: colors.green,
    borderRadius: 8,
    boxShadow: '0 14px 28px rgba(17, 125, 238, 0.28)',
    minHeight: 54,
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  authPrimaryButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 21,
  },
  authSecondaryButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255 255 255 / 0.08)',
    borderColor: 'rgba(191 223 255 / 0.28)',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 52,
    justifyContent: 'center',
    paddingHorizontal: 16,
    paddingVertical: 13,
  },
  authSecondaryButtonText: {
    color: colors.mintLight,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 20,
  },
  loginStage: {
    alignSelf: 'center',
    gap: 14,
    maxWidth: 430,
    width: '100%',
  },
  loginHeaderRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  authBackButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255 255 255 / 0.08)',
    borderColor: 'rgba(191 223 255 / 0.26)',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  authBackButtonText: {
    color: colors.mintLight,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 17,
  },
  loginBadge: {
    backgroundColor: 'rgba(191 223 255 / 0.14)',
    borderColor: colors.glassBorder,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  loginBadgeText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 16,
  },
  loginCard: {
    backgroundColor: 'rgba(255 255 255 / 0.94)',
    borderColor: 'rgba(191 223 255 / 0.26)',
    borderRadius: 8,
    borderWidth: 1,
    boxShadow: '0 18px 42px rgba(0, 8, 20, 0.24)',
    gap: 14,
    padding: 18,
  },
  loginTitle: {
    color: colors.ink,
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 36,
  },
  loginSubtitle: {
    color: colors.textSoft,
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 21,
  },
  authSubmitButton: {
    marginTop: 2,
  },
  authDividerRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    paddingVertical: 2,
  },
  authDividerLine: {
    backgroundColor: colors.cardBorder,
    flex: 1,
    height: 1,
  },
  authDividerText: {
    color: colors.textSoft,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 16,
  },
  socialButtonStack: {
    gap: 9,
  },
  socialButton: {
    alignItems: 'center',
    backgroundColor: colors.inputBackground,
    borderColor: colors.controlBorder,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 50,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  socialButtonMark: {
    alignItems: 'center',
    backgroundColor: colors.ink,
    borderRadius: 8,
    height: 30,
    justifyContent: 'center',
    width: 30,
  },
  socialButtonMarkText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 18,
  },
  socialButtonText: {
    color: colors.ink,
    flex: 1,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 19,
  },
  header: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
  },
  heroCard: {
    backgroundColor: colors.white,
    borderColor: colors.cardBorder,
    borderRadius: 8,
    borderWidth: 1,
    boxShadow: '0 16px 36px rgba(3, 37, 78, 0.16)',
    minHeight: 174,
    overflow: 'hidden',
    padding: 18,
  },
  heroLayerBack: {
    backgroundColor: colors.greenSoft,
    borderRadius: 8,
    height: 98,
    position: 'absolute',
    right: -22,
    top: -18,
    transform: [{rotate: '-12deg'}],
    width: 184,
  },
  heroLayerFront: {
    backgroundColor: colors.successSoft,
    borderColor: colors.successBorder,
    borderRadius: 8,
    borderWidth: 1,
    bottom: -20,
    height: 74,
    left: 18,
    position: 'absolute',
    transform: [{rotate: '5deg'}],
    width: 164,
  },
  heroContent: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'space-between',
  },
  heroTextBlock: {
    flex: 1,
    gap: 7,
  },
  heroSubtitle: {
    color: colors.textSoft,
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 20,
    maxWidth: 245,
  },
  eyebrow: {
    color: colors.green,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
  },
  title: {
    color: colors.ink,
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 39,
    maxWidth: 280,
  },
  statusPill: {
    alignItems: 'center',
    backgroundColor: colors.ink,
    borderRadius: 8,
    boxShadow: '0 10px 20px rgba(3, 37, 78, 0.20)',
    minWidth: 74,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  statusLabel: {
    color: colors.mintLight,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0,
  },
  statusNumber: {
    color: colors.white,
    fontSize: 24,
    fontVariant: ['tabular-nums'],
    fontWeight: '900',
    letterSpacing: 0,
  },
  appBarShell: {
    minHeight: 66,
    position: 'relative',
  },
  screenTabs: {
    alignItems: 'center',
    backgroundColor: colors.glassSurface,
    borderColor: colors.glassBorder,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    borderWidth: 1,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 34,
    boxShadow: '0 10px 22px rgba(3, 37, 78, 0.34)',
    flexDirection: 'row',
    gap: 4,
    minHeight: 58,
    overflow: 'hidden',
    paddingLeft: 10,
    paddingRight: 62,
    paddingVertical: 6,
  },
  screenTab: {
    alignItems: 'center',
    borderRadius: 8,
    flex: 1,
    gap: 3,
    justifyContent: 'center',
    minHeight: 44,
    zIndex: 2,
  },
  screenTabActive: {
    backgroundColor: 'rgba(191 223 255 / 0.10)',
    transform: [{perspective: 260}, {translateY: -2}, {rotateX: '4deg'}],
  },
  liquidBlobOne: {
    backgroundColor: colors.glassHighlight,
    borderRadius: 52,
    height: 58,
    left: 10,
    position: 'absolute',
    top: -15,
    width: 112,
    zIndex: 0,
  },
  liquidBlobTwo: {
    backgroundColor: colors.blueSoft,
    borderRadius: 46,
    bottom: -26,
    height: 66,
    position: 'absolute',
    right: 42,
    width: 98,
    zIndex: 0,
  },
  liquidSheen: {
    backgroundColor: colors.glassSheen,
    height: 104,
    left: 0,
    position: 'absolute',
    top: -24,
    width: 26,
    zIndex: 1,
  },
  appBarIcon: {
    alignItems: 'center',
    borderColor: colors.mintLight,
    borderRadius: 12,
    borderWidth: 1.5,
    backgroundColor: 'rgba(255 255 255 / 0.06)',
    height: 24,
    justifyContent: 'center',
    width: 24,
  },
  appBarIconActive: {
    backgroundColor: colors.mintLight,
    borderColor: colors.mintLight,
  },
  appBarIconText: {
    color: colors.mintLight,
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 12,
  },
  appBarIconTextActive: {
    color: colors.ink,
  },
  screenTabText: {
    color: colors.white,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 13,
  },
  screenTabTextActive: {
    color: colors.mintLight,
  },
  activeTabLine: {
    backgroundColor: colors.transparentAccent,
    borderRadius: 4,
    height: 3,
    marginTop: 1,
    width: 38,
  },
  activeTabLineVisible: {
    backgroundColor: colors.leafAccent,
  },
  appBarAction: {
    alignItems: 'center',
    backgroundColor: colors.glassAction,
    borderColor: colors.appBackground,
    borderRadius: 25,
    borderWidth: 3,
    boxShadow: '0 10px 22px rgba(3, 37, 78, 0.36)',
    height: 50,
    justifyContent: 'center',
    position: 'absolute',
    right: 8,
    top: -12,
    width: 50,
    zIndex: 4,
  },
  appBarActionText: {
    color: colors.white,
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 34,
  },
  appBarActionIcon: {
    height: 34,
    width: 34,
  },
  paletteStrip: {
    backgroundColor: colors.white,
    borderColor: colors.cardBorder,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    padding: 8,
  },
  paletteSwatch: {
    borderRadius: 7,
    flex: 1,
    height: 32,
  },
  card: {
    backgroundColor: colors.white,
    borderColor: colors.cardBorder,
    borderRadius: 8,
    borderWidth: 1,
    boxShadow: '0 10px 24px rgba(3, 37, 78, 0.10)',
    gap: 14,
    padding: 16,
  },
  breathCard: {
    backgroundColor: colors.warmWhite,
  },
  cardHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  sectionTitle: {
    color: colors.ink,
    fontSize: 19,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 24,
  },
  subtleText: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 18,
  },
  bodyText: {
    color: colors.textStrong,
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 22,
  },
  levelRow: {
    flexDirection: 'row',
    gap: 8,
  },
  levelButton: {
    alignItems: 'center',
    aspectRatio: 1,
    backgroundColor: colors.greenSoft,
    borderColor: colors.greenBorder,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
  },
  levelButtonSelected: {
    backgroundColor: colors.green,
    borderColor: colors.green,
  },
  levelButtonText: {
    color: colors.levelText,
    fontSize: 18,
    fontVariant: ['tabular-nums'],
    fontWeight: '800',
    letterSpacing: 0,
  },
  levelButtonTextSelected: {
    color: colors.white,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.green,
    borderRadius: 8,
    minWidth: 78,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  primaryButtonActive: {
    backgroundColor: colors.danger,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
  },
  ghostButton: {
    alignItems: 'center',
    backgroundColor: colors.greenSoft,
    borderColor: colors.greenBorder,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  ghostButtonText: {
    color: colors.green,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  registrationBadge: {
    backgroundColor: colors.blueSoft,
    borderColor: colors.blueBorder,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  registrationBadgeText: {
    color: colors.blueInk,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 15,
  },
  formGroup: {
    gap: 7,
  },
  inputLabel: {
    color: colors.textStrong,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 17,
  },
  textInput: {
    backgroundColor: colors.inputBackground,
    borderColor: colors.controlBorder,
    borderRadius: 8,
    borderWidth: 1,
    color: colors.ink,
    fontSize: 16,
    fontWeight: '700',
    minHeight: 50,
    paddingHorizontal: 12,
    paddingVertical: 11,
  },
  breathArea: {
    alignItems: 'center',
    height: 220,
    justifyContent: 'center',
    overflow: 'hidden',
  },
  breathOrb: {
    backgroundColor: colors.breathOrb,
    borderColor: colors.breathOrbBorder,
    borderRadius: 110,
    borderWidth: 1,
    height: 172,
    position: 'absolute',
    width: 172,
  },
  breathTextWrap: {
    alignItems: 'center',
    gap: 4,
    maxWidth: 210,
  },
  breathPhase: {
    color: colors.ink,
    fontSize: 24,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 30,
  },
  breathSeconds: {
    color: colors.ink,
    fontSize: 52,
    fontVariant: ['tabular-nums'],
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 58,
  },
  groundingList: {
    gap: 8,
  },
  groundingItem: {
    alignItems: 'center',
    backgroundColor: colors.inputBackground,
    borderColor: colors.cardBorder,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 74,
    padding: 12,
  },
  groundingCount: {
    color: colors.ink,
    fontSize: 26,
    fontVariant: ['tabular-nums'],
    fontWeight: '900',
    letterSpacing: 0,
    minWidth: 32,
    textAlign: 'center',
  },
  groundingCopy: {
    flex: 1,
    gap: 3,
  },
  groundingTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 20,
  },
  groundingCue: {
    color: colors.textSoft,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 18,
  },
  doneText: {
    color: colors.white,
  },
  choiceWrap: {
    gap: 8,
  },
  choiceButton: {
    backgroundColor: colors.inputBackground,
    borderColor: colors.cardBorder,
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  choiceButtonSelected: {
    backgroundColor: colors.blueSoft,
    borderColor: colors.blue,
  },
  choiceButtonText: {
    color: colors.textStrong,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 19,
  },
  choiceButtonTextSelected: {
    color: colors.blueInk,
  },
  nextStepPanel: {
    backgroundColor: colors.warmSoft,
    borderColor: colors.warmBorder,
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  nextStepLabel: {
    color: colors.warmInk,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 16,
  },
  nextStepText: {
    color: colors.warmDark,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 22,
  },
  actionGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  actionButton: {
    backgroundColor: colors.actionSoft,
    borderColor: colors.actionBorder,
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 44,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  actionButtonSelected: {
    backgroundColor: colors.ink,
    borderColor: colors.ink,
  },
  actionButtonText: {
    color: colors.textStrong,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 18,
  },
  actionButtonTextSelected: {
    color: colors.white,
  },
  selectedActionPanel: {
    backgroundColor: colors.successSoft,
    borderColor: colors.successBorder,
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  selectedActionText: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 23,
  },
  botIntroPanel: {
    backgroundColor: colors.successSoft,
    borderColor: colors.successBorder,
    borderRadius: 8,
    borderWidth: 1,
    boxShadow: '0 10px 24px rgba(3, 37, 78, 0.10)',
    gap: 8,
    padding: 16,
  },
  chatList: {
    gap: 10,
  },
  chatBubble: {
    borderRadius: 8,
    borderWidth: 1,
    boxShadow: '0 6px 16px rgba(3, 37, 78, 0.08)',
    gap: 5,
    maxWidth: '88%',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  botBubble: {
    alignSelf: 'flex-start',
    backgroundColor: colors.greenSoft,
    borderColor: colors.greenBorder,
  },
  userBubble: {
    alignSelf: 'flex-end',
    backgroundColor: colors.ink,
    borderColor: colors.ink,
  },
  chatSender: {
    color: colors.levelText,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 14,
  },
  userChatSender: {
    color: colors.mintLight,
  },
  chatText: {
    color: colors.textStrong,
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 20,
  },
  userChatText: {
    color: colors.white,
  },
  chatComposer: {
    gap: 10,
  },
  chatInput: {
    minHeight: 84,
    textAlignVertical: 'top',
  },
  chatSendButton: {
    minHeight: 46,
  },
  switchRow: {
    alignItems: 'center',
    backgroundColor: colors.inputBackground,
    borderColor: colors.cardBorder,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 72,
    padding: 12,
  },
  switchCopy: {
    flex: 1,
    gap: 3,
  },
  reviewList: {
    borderColor: colors.cardBorder,
    borderRadius: 8,
    borderWidth: 1,
    overflow: 'hidden',
  },
  reviewRow: {
    alignItems: 'center',
    backgroundColor: colors.inputBackground,
    borderBottomColor: colors.cardBorder,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  reviewLabel: {
    color: colors.textSoft,
    flex: 1,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 17,
  },
  reviewValue: {
    color: colors.ink,
    flex: 1.35,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 19,
    textAlign: 'right',
  },
  submitButton: {
    alignItems: 'center',
    backgroundColor: colors.green,
    borderRadius: 8,
    minHeight: 50,
    justifyContent: 'center',
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  submitButtonDisabled: {
    backgroundColor: colors.greenDisabled,
  },
  submitButtonText: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 20,
  },
  formHint: {
    color: colors.warmInk,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 18,
  },
  successPanel: {
    backgroundColor: colors.successSoft,
    borderColor: colors.successBorder,
    borderRadius: 8,
    borderWidth: 1,
    gap: 4,
    padding: 12,
  },
  successTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 20,
  },
  successText: {
    color: colors.textStrong,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 19,
  },
  videoScreen: {
    gap: 14,
  },
  videoIntroPanel: {
    backgroundColor: colors.white,
    borderColor: colors.cardBorder,
    borderRadius: 8,
    borderWidth: 1,
    boxShadow: '0 10px 24px rgba(3, 37, 78, 0.10)',
    gap: 6,
    padding: 16,
  },
  videoFeed: {
    gap: 14,
  },
  videoCard: {
    backgroundColor: colors.white,
    borderColor: colors.cardBorder,
    borderRadius: 8,
    borderWidth: 1,
    boxShadow: '0 14px 30px rgba(3, 37, 78, 0.14)',
    gap: 12,
    overflow: 'hidden',
    padding: 10,
  },
  videoFrame: {
    backgroundColor: colors.ink,
    borderRadius: 8,
    height: 370,
    justifyContent: 'space-between',
    overflow: 'hidden',
    padding: 14,
  },
  videoPlayer: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  videoMissingNativePanel: {
    alignItems: 'center',
    backgroundColor: colors.ink,
    bottom: 0,
    justifyContent: 'center',
    left: 0,
    padding: 20,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  videoMissingNativeText: {
    color: colors.mintLight,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 21,
    textAlign: 'center',
  },
  videoFrameShade: {
    backgroundColor: 'rgba(0 8 20 / 0.34)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  videoFrameTopRow: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    zIndex: 2,
  },
  videoCategoryPill: {
    backgroundColor: 'rgba(255 255 255 / 0.14)',
    borderColor: colors.glassBorder,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  videoCategoryText: {
    color: colors.white,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 16,
  },
  videoDurationText: {
    color: colors.mintLight,
    fontSize: 12,
    fontVariant: ['tabular-nums'],
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 16,
  },
  videoCenterControl: {
    alignItems: 'center',
    gap: 10,
    justifyContent: 'center',
    zIndex: 2,
  },
  videoErrorText: {
    color: colors.mintLight,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 18,
    textAlign: 'center',
  },
  videoPlayButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255 255 255 / 0.18)',
    borderColor: colors.glassBorder,
    borderRadius: 40,
    borderWidth: 1,
    height: 76,
    justifyContent: 'center',
    width: 76,
  },
  videoPlayButtonText: {
    color: colors.white,
    fontSize: 27,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 32,
  },
  videoFrameCopy: {
    gap: 7,
    zIndex: 2,
  },
  videoTitle: {
    color: colors.white,
    fontSize: 27,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 32,
  },
  videoCue: {
    color: colors.mintLight,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 21,
  },
  videoStepRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    paddingHorizontal: 2,
    paddingBottom: 2,
  },
  videoStepPill: {
    backgroundColor: colors.greenSoft,
    borderColor: colors.greenBorder,
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  videoStepText: {
    color: colors.green,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 16,
  },
  footerPanel: {
    backgroundColor: colors.footerBackground,
    borderColor: colors.cardBorder,
    borderRadius: 8,
    borderWidth: 1,
    padding: 13,
  },
  footerText: {
    color: colors.footerText,
    fontSize: 12,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 18,
  },
});
